#!/usr/bin/env python3

from pathlib import Path
from subprocess import PIPE, run
import shutil
import json

results = {
    "score": 0,
    "tests": []
}

def comp_check() -> bool:
    shutil.copy("/autograder/source/main.cpp", "/autograder/submission")

    res = {
        "name": "Compilation check",
        "visibility": "visible",
    }

    proc = run(["make"], cwd="/autograder/submission",
                stdout=PIPE, stderr=PIPE, text=True)

    if proc.returncode != 0:
        res["status"] = "failed"
        res["output"] = f"Compilation failed.\n-- stdout --\n{proc.stdout}\n-- stderr --\n{proc.stderr}"
        results["tests"].append(res)
        return False

    res["status"] = "passed"
    results["tests"].append(res)
    results["score"] += 1
    return True


def run_tests():
    proc = run(["./main"], cwd="/autograder/submission", stdout=PIPE, stderr=PIPE, text=True)
    res = {
        "name": f"Testcases",
        "visibility": "visible",
        "score": 0.0,
        "max_score": 3.0,
        "status": "passed",
    }

    if proc.returncode != 0:
        res["status"] = "failed"
        res["output"] = f"-- stdout --\n{proc.stdout}"
        results["tests"].append(res)
        return

    score = proc.stdout.count("passed")
    res["score"] = score
    results["tests"].append(res)
    results["score"] += score


if comp_check():
    run_tests()

with open("/autograder/results/results.json", "w") as f:
    json.dump(results, f)
